/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/sessions": {
    post: operations["createSession"];
  };
  "/api/v1/users": {
    post: operations["createUser"];
  };
  "/api/v1/addTeamClick/{teamId}": {
    post: operations["addTeamClick"];
  };
  "/api/v1/teams": {
    get: operations["getTeams"];
  };
  "/api/v1/teams/{teamId}": {
    get: operations["getTeamByTeamId"];
  };
}

export interface components {
  schemas: {
    User: {
      /** @example 2309234802 */
      id: string;
      /** @example john@doe.com */
      email: string;
    };
    Team: {
      /** @example Team */
      name: string;
      /** @example 23409823 */
      id: string;
    };
    ClickCount: {
      /** @example 1000 */
      clickCount: number;
    };
    HttpError: {
      message?: string;
      status?: number;
      errorCode?: string;
      errorData?: {
        message?: string;
        code?: string;
      };
      errorClass?: string;
      stack?: string;
    };
    U4000: {
      /** @example U4000 */
      code?: string;
    };
    U4001: {
      /** @example U4001 */
      code?: string;
    };
    T4001: {
      /** @example T4001 */
      code?: string;
    };
  };
  responses: {
    /** Unauthorized access */
    UnauthorizedErrorResponse: {
      content: {
        "application/json": components["schemas"]["HttpError"];
      };
    };
    /** Unauthorized access */
    NotAuthenticatedErrorResponse: {
      content: {
        "application/json": components["schemas"]["HttpError"];
      };
    };
    /** Request not processed - bad_request */
    BadRequestErrorResponse: {
      content: {
        "application/json": components["schemas"]["HttpError"];
      };
    };
    /** Entity not found - not_found */
    NotFoundErrorResponse: {
      content: {
        "application/json": components["schemas"]["HttpError"];
      };
    };
  };
  parameters: {
    Id: string;
  };
}

export interface operations {
  createSession: {
    responses: {
      /** ok */
      200: {
        content: {
          "application/json": {
            /** @example MjE5NjE5ZGQtOTY5Yi00NWRiLWFkYjgtMGJmMGU4MGM4MDUw */
            token: string;
          };
        };
      };
      400: components["responses"]["BadRequestErrorResponse"];
      404: components["responses"]["NotFoundErrorResponse"];
    };
    requestBody: {
      content: {
        "application/json": {
          /** @example john@doe.com */
          email: string;
        };
      };
    };
  };
  createUser: {
    responses: {
      /** ok */
      200: {
        content: {
          "application/json": {
            /** @example caeb2a6a-bd1d-41cc-bfdf-5d4514ace591 */
            token?: string;
          } & components["schemas"]["User"] & {
              token: unknown;
            };
        };
      };
      400: components["responses"]["BadRequestErrorResponse"];
      /** Invalid data */
      422: {
        content: {
          "application/json": Partial<components["schemas"]["U4000"]> &
            Partial<components["schemas"]["U4001"]> &
            Partial<components["schemas"]["T4001"]>;
        };
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** @example john@doe.com */
          email: string;
          /** @example Abinader */
          teamName: string;
        };
      };
    };
  };
  addTeamClick: {
    parameters: {
      path: {
        /** Unique team ID. See `/teams` */
        teamId: string;
      };
    };
    responses: {
      /** ok */
      200: unknown;
      400: components["responses"]["BadRequestErrorResponse"];
      401: components["responses"]["NotAuthenticatedErrorResponse"];
      403: components["responses"]["UnauthorizedErrorResponse"];
    };
  };
  getTeams: {
    responses: {
      /** ok */
      200: {
        content: {
          "application/json": (components["schemas"]["Team"] &
            components["schemas"]["ClickCount"] & {
              users: (components["schemas"]["User"] &
                components["schemas"]["ClickCount"])[];
            })[];
        };
      };
      400: components["responses"]["BadRequestErrorResponse"];
    };
  };
  getTeamByTeamId: {
    parameters: {
      path: {
        /** Unique team ID. See `/teams` */
        teamId: string;
      };
    };
    responses: {
      /** ok */
      200: {
        content: {
          "application/json": components["schemas"]["Team"] &
            components["schemas"]["ClickCount"] & {
              users: (components["schemas"]["User"] &
                components["schemas"]["ClickCount"])[];
            };
        };
      };
      400: components["responses"]["BadRequestErrorResponse"];
    };
  };
}

export interface external {}
