name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: actions/setup-node@v3
        with:
          node-version: 16.8.1
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
        
